# Generated by Django 4.1.7 on 2023-08-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_remove_stock_products_stock_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='products',
        ),
    ]
