# Generated by Django 4.1.7 on 2023-08-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_remove_stock_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ManyToManyField(through='logistic.StockProduct', to='logistic.product'),
        ),
    ]
