# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта 1
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "peпа",
  "description": "peпа"
}

###

# получение продуктов 2
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта 3
PATCH {{baseUrl}}/products/8/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта 4
DELETE {{baseUrl}}/products/10/
Content-Type: application/json

###

# поиск продуктов по названию и описанию 5
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "мой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 11,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 12,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/7/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=8
Content-Type: application/json
